
# Basic Info
title: Republic of Pwning
description: Hacking, Reversing, Exploiting, CTFs...
email: devnull@rop.la

# URL Configs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social Networks
twitter_username: rop_la
github_username:  rop-la
youtube_channel:  UCg01TfhxLro71ppULtIBAjw

# Post Configs
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown

# theme: minima
plugins:
  - jekyll-feed
