title: "Republic of Pwning"
email: devnull@rop.la
author: "Republic of Pwning"
description: "Reversing, exploiting, pentesting, ctf writeups... && ++hacking"
logo: "/assets/img/logo.png"
icon: "/assets/img/favicon.ico"
icon_16: "/assets/img/favicon-16x16.png"
icon_32: "/assets/img/favicon-32x32.png"

url: "https://blog.rop.la"
baseurl: ""

markdown: kramdown
highlighter: rouge
paginate: 3

plugins:
  - jekyll-paginate
