# Basic Info
title: Republic of Pwning
description: Hacking, Reversing, Exploiting, CTFs...
keywords: hacking, ctf, reversing, exploits, writeup
author: RoP Team
email: team@rop.la
lang: en  # default language

# URL Configs
url: "https://blog.rop.la"
baseurl: ""

# Social Networks
twitter_username: rop_la
github_username:  rop-la
youtube_channel:  UCg01TfhxLro71ppULtIBAjw

# Post Configs
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown

# theme: minima
plugins:
  - jekyll-feed
