title: Republic of Pwning (RoP) Blog
email: blog@rop.la
description: >- # this means to ignore newlines until "baseurl:"
  Blog about exploiting, researching, CTF competitions and more!
  Team ROP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.rop.la" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rop_la
github_username:  rop-la

# Build settings
markdown: kramdown
#theme: jekyll-theme-hacker
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
