title: "Republic of Pwning"
email: devnull@rop.la
author: "Republic of Pwning"
description: "Reversing, exploiting, pentesting, ctf writeups... && ++hacking"
desc: 'Reversing, exploiting, pentesting, ctf writeups... && ++hacking

Follow us on our twitter account <a href="https://twitter.com/rop_la"><i class="fab fa-twitter"></i>@rop-la</a>, our public Github repositories <a href="https://github.com/rop-la/"><i class="fab fa-github"></i>RoP-LA</a> and <a href="https://www.youtube.com/channel/UCg01TfhxLro71ppULtIBAjw"><i class="fab fa-youtube"></i>Youtube Channel</a>.'

keywords: "reversing, exploiting, pentesting, ctf, writeups, hacking"

excerpt_separator: "<!--more-->"
logo: "/assets/img/logo.png"
icon: "/assets/img/favicon.ico"
icon_16: "/assets/img/favicon-16x16.png"
icon_32: "/assets/img/favicon-32x32.png"

url: "https://blog.rop.la"
baseurl: ""

markdown: kramdown
highlighter: rouge
paginate: 3

plugins:
  - jekyll-paginate
